const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(path.join(__dirname,'../research/tools/ui-test/node_modules/playwright')));}
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,data)=>{if(error)return res.writeHead(404).end();res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream'});res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try{for(const shell of ['index.html','classic.html']){const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));if(process.env.LEGACY==='1')await context.addInitScript(()=>localStorage.setItem('droid-archive-ui-style','legacy'));await context.addInitScript(ids=>localStorage.setItem('droid-archive-seen-patch-notes',JSON.stringify(ids)),JSON.parse(fs.readFileSync(path.join(root,'data/patch-notes.json'),'utf8')).notes.map(n=>n.id));await context.addInitScript(()=>{const OriginalDate=Date;globalThis.Date=class extends OriginalDate{constructor(...args){super(...(args.length?args:['2026-09-26T21:00:00Z']))}static now(){return new OriginalDate('2026-09-26T21:00:00Z').getTime()}};});await page.route('https://**/*',r=>r.abort());await page.route('**/app.js*',r=>r.fulfill({contentType:'text/javascript',body:source+'\nwindow.kyberTest={state,variantRank,nextVariant,chipsToVariant,upgradeChipRate,chipSellValue,applyProfileData,validateBaseImport,baseExport,incomeForPlaced,placements,optimiseBase,optimisedPlacements,blankProfileData,recordDroidex,recordDroidexUpgrade,droidexEntry,showCardVariantModal,changeOwnedUnitVariant,fusionOutcome,route,save,hasRequirement,requirementStatus,rebirthTrackerStatus,profileRequirementReady,kyberActivationCost,profileRequirementAction,nextRebirthHoldBacks,chipSellCalculatorHtml};'}));
await page.goto(`http://127.0.0.1:${server.address().port}/${shell}#/kyber`);await page.waitForFunction(()=>window.kyberTest?.state.droids.length===92);await page.evaluate(()=>document.querySelector('#patchNotesClose')?.click());
const result=await page.evaluate(()=>{const t=window.kyberTest,s=t.state,mouse=s.droids.find(d=>d.name==='MOUSE');if(Object.values(s.rebirths).some(rows=>rows.length!==40))throw Error('Missing rebirths');if(s.droids.some(d=>d.rarity==='ICONIC'&&d.variants.KYBER))throw Error('Iconic Kyber');
for(const d of s.droids.filter(d=>d.rarity!=='ICONIC')){for(const [v,m] of [['KYBER_GREEN',3],['KYBER_BLUE',3.25],['KYBER_PURPLE',3.6]])if(Math.abs(d.variants[v].income-d.variants.KYBER.income*m)>1e-5)throw Error('Colour income '+d.name);}
if(t.nextVariant('STELLAR')!=='KYBER'||t.nextVariant('KYBER_GREEN')!==null||t.variantRank('KYBER_BLUE')!==t.variantRank('KYBER'))throw Error('Colour treated as tier');if(t.chipsToVariant(mouse,'STELLAR','KYBER_PURPLE')!==240||t.chipsToVariant(mouse,'KYBER_GREEN','KYBER_PURPLE')!==0)throw Error('Chip upgrade tier');
const rows=[{name:'MOUSE',variant:'KYBER_GREEN',qty:1,preferred:'WORKER',preferredSlot:0,built:true},{name:'MOUSE',variant:'KYBER_PURPLE',qty:1,preferred:'LOUNGE',preferredSlot:0,built:true},{name:'PIT',variant:'STELLAR',qty:1,preferred:'WORKER',preferredSlot:1,built:true}];t.applyProfileData({...t.blankProfileData(),owned:rows,rebirth:35,superRebirthGoal:40});const before=t.placements();const income=t.incomeForPlaced(before.placed);if(income<200)throw Error('Missing activated income');const exported=t.validateBaseImport(t.baseExport());if(exported.owned[0].variant!=='KYBER_GREEN'||exported.superRebirthGoal!==40)throw Error('Import lost Kyber');t.recordDroidex('MOUSE','KYBER_GREEN');if(!t.droidexEntry('MOUSE','KYBER')||!t.droidexEntry('MOUSE','KYBER_GREEN')||t.droidexEntry('MOUSE','KYBER_BLUE'))throw Error('Collection colours conflated');
const plan=t.optimiseBase(before),projected=t.optimisedPlacements(before,plan),after=t.incomeForPlaced(projected.placed);if(after+1e-6<income)throw Error('Optimise loses income');if(t.fusionOutcome(Array(3).fill({name:'MOUSE',variant:'KYBER_PURPLE'})).kind!=='unknown')throw Error('Assumes colour fusion');return{income,after,mouseCost:mouse.variants.KYBER.cost,mouseIncome:mouse.variants.KYBER.income};});assert.equal(result.mouseCost,34200);assert.equal(result.mouseIncome,70.4);
// Manual Rebirth tracking needs one Kyber tier button and must not edit Base.
await page.evaluate(()=>{location.hash='#/rebirth';});await page.waitForTimeout(150);const ownedBefore=await page.evaluate(()=>JSON.stringify(window.kyberTest.state.owned));await page.locator('#toggleManualRebirth').check();const strip=page.locator('.rebirth-quality-strip').first();assert.equal(await strip.locator('button').count(),8);await strip.locator('[data-variant="KYBER"]').click();assert.equal(await page.locator('.rebirth-quality-strip').first().locator('[data-variant="KYBER"]').getAttribute('aria-pressed'),'true');assert.equal(await page.evaluate(()=>JSON.stringify(window.kyberTest.state.owned)),ownedBefore);await page.locator('#toggleManualRebirth').uncheck();
await page.evaluate(()=>{window.kyberTest.state.novaUpgrades['blueprint-scrap']=4;location.hash='#/nova-shop/blueprint-scrap';});const scrapLevel=page.locator('tr').filter({hasText:'Level 5'});await scrapLevel.waitFor();assert.match(await scrapLevel.innerText(),/400/);assert(!(await page.locator('#novaLevelUp').isDisabled()));await page.locator('#novaLevelUp').click();assert(await page.locator('#novaLevelUp').isDisabled());
for(const route of ['/droid/mouse','/base','/optimise','/rebirth','/droidex','/nova-shop','/cantina-shop','/kyber']){await page.evaluate(route=>{location.hash='#'+route;},route);await page.waitForTimeout(180);assert(!/Archive unavailable/.test(await page.locator('#app').innerText()),route);}
await page.evaluate(()=>{location.hash='#/droid/mouse';});await page.waitForTimeout(150);await page.locator('[data-v="KYBER_PURPLE"]').click();assert.match(await page.locator('#app').innerText(),/Kyber Purple/);await page.locator('[data-v="KYBER"]').click();const inactive=page.locator('.info-image img[data-kyber-colour="inactive"]');assert.equal(await inactive.count(),1);assert.match(await inactive.evaluate(img=>getComputedStyle(img).filter),/grayscale\(1\)/);for(const colour of ['GREEN','BLUE','PURPLE']){await page.locator(`[data-v="KYBER_${colour}"]`).click();const portrait=page.locator(`.info-image img[data-kyber-colour="${colour.toLowerCase()}"]`);assert.equal(await portrait.count(),1);assert(await portrait.evaluate(img=>img.complete&&img.naturalWidth>0));if(colour!=='GREEN')assert.match(await portrait.evaluate(img=>getComputedStyle(img).filter),new RegExp('kyber-portrait-'+colour.toLowerCase()));}await page.locator('[data-v="DEFAULT"]').click();assert.equal(await page.locator('.info-image img[data-kyber-colour]').count(),0);await page.evaluate(()=>{const t=window.kyberTest;t.showCardVariantModal(t.placements().placed.find(x=>x.name==='MOUSE'),()=>{});});assert.equal(await page.locator('[data-card-variant="KYBER_BLUE"]').count(),1);await page.locator('[data-card-variant="KYBER_BLUE"]').click();assert.equal(await page.evaluate(()=>window.kyberTest.state.owned.some(x=>x.variant==='KYBER_BLUE')),true);

// Activation must be reflected in both Rebirth and Base Outlook, in both shells.
const activationFixture=await page.evaluate(()=>{const t=window.kyberTest,s=t.state,r=s.rebirths[0].find(r=>r.to===36);t.applyProfileData({...t.blankProfileData(),rebirth:35,superRebirthGoal:40,owned:r.requiredDroids.map(req=>({name:req.droidName,variant:'KYBER',qty:1,built:true}))});location.hash='#/base';t.route();return r.requiredDroids.map(req=>({name:req.droidName,cost:t.kyberActivationCost(s.droids.find(d=>d.name===req.droidName))}));});
await page.waitForTimeout(200);
assert.equal(await page.locator('.outlook-next-card.ready').count(),0);
assert.equal(await page.locator('.outlook-next-card').count(),3);
await page.evaluate(()=>{const t=window.kyberTest,s=t.state,r=s.rebirths[0].find(r=>r.to===36);for(const req of r.requiredDroids){const text=t.profileRequirementAction({owned:s.owned},0,36,req);if(!text.includes('Activate')||!text.includes('Kyber Crystal'))throw Error('Shared Outlook missing activation');}const html=t.chipSellCalculatorHtml(t.placements());if(!html.includes('Activate'))throw Error('Rebirth preparation missing activation');});
fs.mkdirSync(path.join(root,'research/uefn/september27/ui'),{recursive:true});await page.locator('.rebirth-summary-box').first().screenshot({path:path.join(root,'research/uefn/september27/ui',shell+'-outlook.png')});
for(const req of activationFixture){const card=page.locator('.outlook-next-card').filter({hasText:req.name});assert.match(await card.innerText(),/Kyber.*\(active\)/);assert.match(await card.innerText(),new RegExp('Activate.*'+req.cost+' Kyber Crystal'));assert(!/upgrade 0 chips/i.test(await card.innerText()));}
await page.evaluate(()=>{location.hash='#/rebirth';});await page.waitForTimeout(200);
const group=page.locator('.rebirth-detail-group').filter({has:page.locator('h2',{hasText:'Rebirth: 36'})});assert(!/\bready\b/.test(await group.getAttribute('class')));assert.match(await group.innerText(),/Activate/);
// Manual inactive is not ready; explicit Active is saved and shared-profile compatible.
await page.locator('#toggleManualRebirth').check();
const manual=page.locator('.rebirth-detail-group').filter({has:page.locator('h2',{hasText:'Rebirth: 36'})});
await manual.locator('[data-variant="KYBER"]').first().click();
assert.match(await manual.locator('.manual-rebirth-requirement').first().innerText(),/Activate/);
await manual.locator('[data-manual-kyber-active]').first().check();
assert.match(await manual.locator('.manual-rebirth-requirement').first().innerText(),/Ready/);
await page.reload();await page.waitForFunction(()=>window.kyberTest?.state.droids.length===92);
assert(await page.locator('[data-manual-kyber-active]').first().isChecked());
await page.locator('[data-manual-kyber-active]').first().uncheck();assert.match(await page.locator('[data-manual-kyber-active]').first().locator('xpath=ancestor::div[contains(@class,"manual-rebirth-requirement")]').innerText(),/Activate/);
await page.locator('#toggleManualRebirth').uncheck();
await page.evaluate(()=>{const t=window.kyberTest;t.state.owned.forEach((r,i)=>r.variant=['KYBER_GREEN','KYBER_BLUE','KYBER_PURPLE'][i]);location.hash='#/base';t.route();});await page.waitForTimeout(150);assert.equal(await page.locator('.outlook-next-card.ready').count(),3);
const costCheck=await page.evaluate(()=>{const t=window.kyberTest,expected={COMMON:1,RARE:2,EPIC:4,LEGENDARY:7,MYTHIC:10};for(const d of t.state.droids){const cost=t.kyberActivationCost(d);if(d.variants.KYBER&&cost!==expected[d.rarity])throw Error('Activation cost '+d.name);if(!d.variants.KYBER&&cost!==null)throw Error('Unsupported activation '+d.name);}return true;});assert(costCheck);
await page.evaluate(()=>{location.hash='#/droid/mouse';});await page.waitForTimeout(150);assert.match(await page.locator('.info-row').filter({hasText:'Kyber activation'}).innerText(),/1 Kyber Crystal/);

await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{location.hash='#/kyber';});await page.waitForTimeout(200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2),'Mobile page overflows');fs.mkdirSync(path.join(root,'research/uefn/september26/new-build/ui'),{recursive:true});await page.screenshot({path:path.join(root,'research/uefn/september26/new-build/ui',shell+'.png'),fullPage:true});assert.deepEqual(errors,[],shell+' browser errors');console.log('PASS',shell,result);await context.close();}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
