const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),src=fs.readFileSync(path.join(root,'app.js'),'utf8');
const line=key=>src.split(/\r?\n/).find(s=>s.startsWith(key));
const fn=key=>{const start=src.indexOf('function '+key+'(');assert(start>=0,key);let depth=0,end=src.indexOf('{',start);for(;end<src.length;end++){if(src[end]==='{')depth++;if(src[end]==='}'&&!--depth)return src.slice(start,end+1);}};
const state={droids:JSON.parse(fs.readFileSync(path.join(root,'data/droids.json'))),fusion:JSON.parse(fs.readFileSync(path.join(root,'data/fusion.json'))),owned:[],droidex:[],novaUpgrades:{},rebirth:20,rebirths:{},cycle:0,superRebirthGoal:35};
const sb={state,console,capacity:()=>1,rebirthGoal:()=>state.superRebirthGoal,futureRequirements:()=>state.requirements||[],rebirthTrackerStatus:(at,req)=>({selected:state.manualVariant,ready:state.manualReady})};vm.createContext(sb);
for(const name of ['VARIANTS','RARITY_LADDER','isIconic','isFusion','fusionDroid','fusionRecipes','fusionRecipeWants','fusionKey','fusionRecipeFor','variantStep','rarityStep','nextVariant','nextRarity','lowestVariant','droidRarity','droidIncomeAt','droidexGapFor','PRODUCTIVE_STATIONS'])vm.runInContext(line('const '+name+'='),sb);
for(const name of ['normaliseNotificationPreferences','normaliseFusionPreferences','notificationCyclePlan','notificationRecommendations','fusionOutcome','fusionCountFrom','fusionBestVariant','fusionQualitySteps','fusionRaritySteps','fusionSpendFrom','fusionBestFrom','fusionChainFromSpares','typicalIncomeFor','droidexEntry'])vm.runInContext(fn(name),sb);
const run=code=>vm.runInContext(code,sb);
const requirements=[{droidName:'R6',variant:'GALACTIC',at:22},{droidName:'KX',variant:'STELLAR',at:34},{droidName:'RIC',variant:'GALACTIC',at:30},{droidName:'R6',variant:'STELLAR',at:35}];
state.requirements=requirements;
assert.equal(run('notificationRecommendations().recommendations.length'),0,'zero free slots');
state.novaUpgrades['droidex-notifications']=1;
let m=run('notificationRecommendations()');assert.equal(m.recommendations[0].name,'R6');assert.equal(m.recommendations[0].variant,'GALACTIC');assert.equal(m.variantWatch,false);
state.novaUpgrades['variant-watch']=1;assert.equal(run('notificationRecommendations().variantWatch'),true);
state.notificationPreferences={priority:'rare'};m=run('notificationRecommendations()');assert.equal(m.recommendations[0].name,'KX','late Mythic beats nearer low-rarity droid');
state.notificationPreferences={priority:'furthest'};m=run('notificationRecommendations()');assert.equal(m.recommendations[0].name,'R6');assert.equal(m.recommendations[0].variant,'STELLAR');
state.novaUpgrades['droidex-notifications']=10;m=run('notificationRecommendations()');assert.equal(m.recommendations.filter(x=>x.name==='R6').length,1,'one slot per droid');
state.owned=[{name:'R6',variant:'STELLAR',qty:1,built:false}];assert(!run('notificationRecommendations().recommendations').some(x=>x.name==='R6'),'owned or building sufficient droid does not need another spawn');
state.owned=[{name:'R6',variant:'DEFAULT',qty:1}];state.notificationPreferences.ownedPolicy='missing';assert(!run('notificationRecommendations().recommendations').some(x=>x.name==='R6'));
state.notificationPreferences.ownedPolicy='upgrades';assert(run('notificationRecommendations().recommendations').some(x=>x.name==='R6'));
state.novaUpgrades['variant-watch']=0;assert(!run('notificationRecommendations().recommendations').some(x=>x.name==='R6'),'without Variant Watch an owned droid is never a new notification target');
state.novaUpgrades['variant-watch']=1;state.notificationPreferences={priority:'rare',includeUpgrades:true};
assert(!run('notificationRecommendations().recommendations').some(x=>x.name==='R6'),'legacy default migrates to missing-only');
state.notificationPreferences={priority:'rare',tracked:[{name:'KX',variant:'STELLAR'}]};state.novaUpgrades['droidex-notifications']=2;
m=run('notificationRecommendations()');assert.equal(m.availableSlots,1);assert.equal(m.recommendations.length,1);assert(!m.recommendations.some(x=>x.name==='KX'));
state.notificationPreferences.tracked.push({name:'MOUSE',variant:null});m=run('notificationRecommendations()');assert.equal(m.availableSlots,0);assert.equal(m.recommendations.length,0,'tracking outside the rebirth list uses a slot');
state.owned.push({name:'KX',variant:'STELLAR'});assert.equal(run('notificationRecommendations().tracked.length'),2,'obtaining a droid does not silently free a game notification slot');
state.novaUpgrades['droidex-notifications']=1;assert.equal(run('notificationRecommendations().recommendations.length'),0,'lowered capacity never yields negative or extra recommendations');
assert.equal(run("normaliseNotificationPreferences({tracked:[{name:'R6'},{name:'R6',variant:'GALACTIC'},null]}).tracked.length"),1);
state.notificationPreferences={priority:'rare'};
state.rebirthTracker={notUsingBase:true};state.manualReady=true;assert.equal(run('notificationRecommendations().recommendations.length'),0);state.rebirthTracker=null;
state.novaUpgrades['droidex-notifications']=100;assert.equal(run('notificationRecommendations().slots'),10);
assert.equal(run("normaliseNotificationPreferences({horizon:-3,priority:'bad'}).horizon"),1);
console.log('PASS: notification capacity, priorities, deduplication, upgrades, Variant Watch and manual tracker');

state.requirements=[{droidName:'LEP',variant:'STELLAR',at:35}];
state.notificationPreferences={priority:'rare',ownedPolicy:'upgrades'};
state.owned=[{name:'LEP',variant:'RAINBOW'}];
m=run('notificationRecommendations()');assert.equal(m.recommendations[0].variant,'STELLAR','existing profiles keep the final requirement as their target');
state.notificationPreferences.upgradeTarget='next';
const ladder=['DEFAULT','GOLD','DIAMOND','RAINBOW','BESKAR','GALACTIC','STELLAR'];
for(let i=0;i<ladder.length-1;i++){
  state.owned=[{name:'LEP',variant:ladder[i]}];m=run('notificationRecommendations()');
  assert.equal(m.recommendations[0].variant,ladder[i+1]);assert.equal(m.recommendations[0].requiredVariant,'STELLAR');
}
state.owned=[{name:'LEP',variant:'STELLAR'}];assert.equal(run('notificationRecommendations().recommendations.length'),0);
state.owned=[];m=run('notificationRecommendations()');assert.equal(m.recommendations[0].variant,'DEFAULT','any copy improves on owning none');assert.equal(m.recommendations[0].requiredVariant,'STELLAR');
state.notificationPreferences.upgradeTarget='required';assert.equal(run('notificationRecommendations().recommendations[0].variant'),'STELLAR','required mode still targets the rebirth requirement');
state.notificationPreferences.upgradeTarget='next';state.notificationPreferences.ownedPolicy='missing';assert.equal(run('notificationRecommendations().recommendations[0].variant'),'STELLAR','disabled upgrade setting does not affect missing-only mode');
state.notificationPreferences.ownedPolicy='upgrades';state.novaUpgrades['variant-watch']=0;assert.equal(run('notificationRecommendations().recommendations[0].variant'),'STELLAR','disabled upgrade setting requires Variant Watch');state.novaUpgrades['variant-watch']=1;
state.owned=[{name:'LEP',variant:'GOLD'},{name:'LEP',variant:'RAINBOW',built:false}];
assert.equal(run('notificationRecommendations().recommendations[0].variant'),'BESKAR','use the strongest owned copy, including builds');
state.notificationPreferences.tracked=[{name:'LEP',variant:'BESKAR'}];state.owned=[{name:'LEP',variant:'BESKAR'}];
m=run('notificationRecommendations()');assert.equal(m.tracked[0].variant,'BESKAR','recorded game threshold must not silently change');assert.equal(m.eligible[0].variant,'GALACTIC');
state.novaUpgrades['variant-watch']=0;assert.equal(run('notificationRecommendations().eligible.length'),0);
state.novaUpgrades['variant-watch']=1;state.notificationPreferences.tracked=[];state.rebirthTracker={notUsingBase:true};state.manualReady=false;state.manualVariant='RAINBOW';state.owned=[];
assert.equal(run('notificationRecommendations().recommendations[0].variant'),'BESKAR','manual tracker ownership supports intermediate upgrades');state.rebirthTracker=null;
assert.equal(run("normaliseNotificationPreferences({upgradeTarget:'invalid'}).upgradeTarget"),'required');
console.log('PASS: intermediate upgrade thresholds, final requirements, best owned copies, manual ownership and unchanged tracked records');

state.owned=[];state.rebirth=0;state.cycle=0;
state.notificationPreferences={startRebirth:11,priority:'next',horizon:3};
state.requirements=[{droidName:'R6',variant:'GOLD',at:10},{droidName:'KX',variant:'BESKAR',at:11},{droidName:'LEP',variant:'STELLAR',at:13},{droidName:'RIC',variant:'GALACTIC',at:14}];
m=run('notificationRecommendations()');assert.deepEqual(Array.from(m.eligible,x=>x.name),['KX','LEP'],'start is inclusive and horizon begins there');
state.notificationPreferences.priority='rare';assert.equal(run('notificationRecommendations().eligible.length'),3);
state.rebirth=11;assert(!run('notificationRecommendations().eligible').some(x=>x.name==='KX'),'completed rebirths stay excluded');
state.rebirths={0:[],1:[{to:10,requiredDroids:[{droidName:'R6',variant:'GOLD'}]},{to:11,requiredDroids:[{droidName:'KX',variant:'BESKAR'},{droidName:'LEP',variant:'STELLAR'}]},{to:20,requiredDroids:[{droidName:'RIC',variant:'GALACTIC'}]}]};
state.notificationPreferences={startRebirth:11,cycles:'next',priority:'rare',upgradeTarget:'next'};state.rebirth=34;
state.owned=[{name:'KX',variant:'STELLAR'},{name:'LEP',variant:'RAINBOW'}];state.rebirthTracker={notUsingBase:true};state.manualReady=true;
const before=JSON.stringify(state.owned);m=run('notificationRecommendations()');
assert.equal(m.eligible.length,3,'current ownership and manual readiness cannot cover next cycle');assert(m.eligible.every(x=>x.nextCycleOnly));
assert.equal(m.eligible.find(x=>x.name==='LEP').variant,'STELLAR','next-cycle target does not assume current lower copy survives');
assert.equal(JSON.stringify(state.owned),before,'planning does not alter inventory');
state.novaUpgrades['variant-watch']=0;assert.equal(run('notificationRecommendations().eligible.length'),3,'droid-only notifications can prepare next cycle');
state.notificationPreferences.tracked=[{name:'KX',variant:null}];state.novaUpgrades['droidex-notifications']=2;
m=run('notificationRecommendations()');assert.equal(m.availableSlots,1);assert.equal(m.recommendations.length,1);assert(!m.recommendations.some(x=>x.name==='KX'));
state.rebirthTracker=null;state.notificationPreferences={startRebirth:11,cycles:'both',priority:'rare'};state.rebirth=20;
state.requirements=[{droidName:'R6',variant:'GALACTIC',at:22},{droidName:'RIC',variant:'GALACTIC',at:30}];
m=run('notificationRecommendations()');assert(m.recommendations.every(x=>!x.nextCycleOnly),'current-cycle needs have priority');assert.equal(m.eligible.filter(x=>x.name==='RIC').length,1,'same droid across cycles uses one notification');
assert.equal(m.eligible.find(x=>x.name==='RIC').needs.length,2);
state.superRebirthGoal=12;assert(!run('notificationRecommendations().eligible').some(x=>x.name==='RIC'),'goal applies to both cycles');state.superRebirthGoal=35;
state.cycle=1;state.notificationPreferences.cycles='next';state.rebirths[0]=state.rebirths[1];m=run('notificationRecommendations()');assert.equal(m.cyclePlan.nextCycle,0,'wraps after final configured cycle');assert(m.eligible.every(x=>x.needs.every(n=>n.cycle===0)));
state.rebirths={1:[]};assert.equal(run('notificationRecommendations().eligible.length'),0,'do not invent unavailable next-cycle data');
assert.equal(run("normaliseNotificationPreferences({startRebirth:99,cycles:'bad'}).startRebirth"),35);assert.equal(run("normaliseNotificationPreferences({startRebirth:0,cycles:'bad'}).cycles"),'current');
const cycleFiles=JSON.parse(fs.readFileSync(path.join(root,'data/rebirth-cycles/index.json'))).cycles;
state.rebirths=Object.fromEntries(cycleFiles.map((file,i)=>[i,JSON.parse(fs.readFileSync(path.join(root,'data/rebirth-cycles',file)))]));
state.cycle=0;state.notificationPreferences={cycles:'next',priority:'rare',startRebirth:11};state.novaUpgrades['droidex-notifications']=10;
state.owned=state.droids.map(d=>({name:d.name,variant:'STELLAR'}));m=run('notificationRecommendations()');
assert.equal(m.recommendations.length,10,'can use all ten slots for the next real cycle even with a complete Base');assert(m.recommendations.every(x=>x.needs.every(n=>n.cycle===1&&n.at>=11)));
state.cycle=cycleFiles.length-1;assert.equal(run('notificationRecommendations().cyclePlan.nextCycle'),0,'real last cycle wraps to Cycle 1');
state.cycle=0;state.rebirths={};state.rebirthTracker=null;
console.log('PASS: inclusive rebirth start, cycle selection, future ownership, shared capacity, deduplication, goal limits and cycle wrap');

state.owned=[];
const batch=(name,count=3,variant='GALACTIC')=>({name,qty:count,variant});
function chain(rows,settings){state.fusionPreferences=settings;sb.rows=rows;return run('fusionChainFromSpares(rows,[])');}
let steps=chain([batch('MECHA-DROID')],{});assert.equal(steps[0].kind,'quality');assert.equal(steps[0].out.variant,'STELLAR');
steps=chain([batch('MECHA-DROID')],{goal:'rarity'});assert.equal(steps.length,0,'cannot relabel three identical droids as a rarity upgrade');
steps=chain([batch('MECHA-DROID'),batch('BB9',2),batch('CYCLO-GRAV',1)],{goal:'rarity'});assert.equal(steps.length,2,'mix all six Legendaries into two Mythic rolls');assert(steps.every(s=>s.kind==='rarity'&&s.rarity==='MYTHIC'&&s.variant==='GALACTIC'));
for(const step of steps){sb.inputs=step.spend.flatMap(p=>Array.from({length:p.count},()=>({name:p.name,variant:p.variant})));assert.equal(run('fusionOutcome(inputs).kind'),'rarity');assert.equal(run('fusionOutcome(inputs).rarity'),'MYTHIC');}
steps=chain([batch('MECHA-DROID'),batch('BB9',2)],{goal:'variant'});assert(steps.every(s=>s.kind==='quality'));
steps=chain([batch('KX',2,'DIAMOND'),batch('RIC',1,'DIAMOND')],{mythics:'reroll'});assert.equal(steps.length,1);assert.equal(steps[0].rarity,'MYTHIC');assert.equal(steps[0].variant,'DIAMOND');assert.equal(steps[0].out,null);
assert.equal(chain([batch('KX',3,'DIAMOND')],{mythics:'reroll'}).length,0,'same-name lower variants are not rerolls');
assert.equal(chain([batch('KX',3,'STELLAR')],{mythics:'reroll'})[0].rarity,'MYTHIC');
assert.equal(chain([batch('KX',3,'STELLAR')],{mythics:'off'}).length,0);
assert.equal(chain([batch('KX',1),batch('IG',1),batch('RIC',1)],{mythics:'reroll'}).length,0,'known RIV-3T recipe cannot masquerade as a random reroll');
steps=chain([batch('KX',1),batch('IG',1),batch('RIC',1),batch('LOADLIFTER',1)],{mythics:'reroll'});assert(steps.length>0,'alternative triple bypasses named recipe');
const counts=new Map();for(const step of steps)for(const part of step.spend)counts.set(part.name,(counts.get(part.name)||0)+part.count);assert([...counts.values()].every(n=>n===1),'no repeated spend');
console.log('PASS: exact fusion batches, rarity versus variant goals, Mythic rerolls, recipe collisions and stock consumption');
